version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
      POSTGRES_DB: your_db_name
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    environment:
      DB_HOST: db
      DB_USER: your_db_user
      DB_PASSWORD: your_db_password
      DB_NAME: your_db_name
    ports:
      - "80:8080"
    volumes:
      - ./output:/app/output
    depends_on:
      - db
    command: ["npm", "start"]

volumes:
  pgdata:
